### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by yepidoodles** [Zerthick/LinkMe#1]
Hello, 

I've tried creating links via the config, however none of them seem to work (I've even used the examples you used in one of your comments on the forum). There's no start up message or error message in the log either.

SpongeForge: 1.12.2-2555-7.1.0-BETA-2831

Alice
DragonTechMC

**Comment by Zerthick** [comment]
I'm unable to reproduce this issue on the latest version of SpongeForge, 1.12.2-2555-7.1.0-BETA-2837
The plugin should generate a sample config file when it is run for the first time, is this not the case?

**Comment by yepidoodles** [comment]
It does generate the config, however the command always appears as an unknown command. I am a few versions behind you on SpongeForge still, so I'll give it an update and give it another try.

**Comment by Zerthick** [comment]
Any updates on this?

**Comment by yepidoodles** [comment]
Sorry, I must have forgotten about this, I never managed to get it to work and gave up with it.

**Comment by Zerthick** [comment]
Out of curiosity what command were you trying to run?

**Comment by yepidoodles** [comment]
I can't remember and I've since deleted the configs, sorry. Decided to just commission someone to update the plugin I made which has the same function.

**Comment by Zerthick** [comment]
Alright then.
