### ISSUE TITLE
Reload Feature

### ISSUE THREAD

**Issue by SirRicharalar** [Zerthick/LinkMe#2]
hello,

I can't reload this pluggin with either /linkme reload OR /sponge plugins relaod. Could you add this feature please so i do not have to reload the server every time i update!

**Comment by Zerthick** [comment]
I agree this would be a nice enhancement. I'll look into this when I have some spare development time.

**Comment by Zerthick** [comment]
Added in [v1.4.0](https://github.com/Zerthick/LinkMe/releases/tag/v1.4.0)! 😄
